- id: system_set_lovelace_theme_on_startup
  alias: "[SYSTEM] Set Lovelace theme on startup"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data:
        name: clear

- id: system_renew_letsencrypt_certificate
  alias: "[SYSTEM] Renew Let's Encrypt certificate"
  trigger:
    - platform: time
      at: 00:00:00
  action:
    - service: hassio.addon_restart
      data:
        addon: core_letsencrypt

- id: system_take_weekly_snapshot
  alias: "[SYSTEM] Take weekly snapshot"
  trigger:
    - platform: time
      at: 02:00:00
  condition:
    - condition: time
      weekday:
        - sun
  action:
    - service: hassio.snapshot_full
      data_template:
        name: Backup_{{ now().strftime('%Y-%m-%d') }}

- id: blinds_close_at_dusk
  alias: "[BLINDS] Close at dusk"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      below: -2.5
  condition:
    - condition: time
      after: "16:30:00"
      before: "23:00:00"
  action:
    - service: cover.close_cover
      entity_id: cover.dining_room
    - service: cover.close_cover
      entity_id: cover.living_room

- id: blinds_open_at_dawn
  alias: "[BLINDS] Open at dawn"
  trigger:
    - platform: sun
      event: sunrise
  condition:
    - condition: time
      before: "10:00:00"
  action:
    - service: cover.open_cover
      entity_id: cover.dining_room
    - service: cover.open_cover
      entity_id: cover.living_room
    - service: cover.open_cover
      entity_id: cover.kitchen

- id: blinds_open_via_living_remote
  alias: "[BLINDS] Open via Living remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room
        event: 1002 # left_upper_short_release
  action:
    - service: cover.open_cover
      entity_id: cover.dining_room
    - service: cover.open_cover
      entity_id: cover.living_room
    - service: cover.open_cover
      entity_id: cover.kitchen

- id: blinds_close_via_living_remote
  alias: "[BLINDS] Close via Living remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room
        event: 2002 # left_lower_short_release
  action:
    - service: cover.close_cover
      entity_id: cover.dining_room
    - service: cover.close_cover
      entity_id: cover.living_room
    - service: cover.close_cover
      entity_id: cover.kitchen

- id: blinds_stop_via_living_remote
  alias: "[BLINDS] Stop via Living remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room
        event: 1003 # left_upper_long_release
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room
        event: 2003 # left_lower_long_release
  action:
    - service: cover.stop_cover
      entity_id: cover.dining_room
    - service: cover.stop_cover
      entity_id: cover.living_room
    - service: cover.stop_cover
      entity_id: cover.kitchen

- id: lights_living_turn_on_at_dusk
  alias: "[LIGHTS - Living] Turn on at dusk"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      below: -1.0
  action:
    - service: script.activate_scene
      data:
        circadian_lighting: switch.circadian_lighting_living_room
        scene: scene.living_room_relax

- id: lights_living_turn_off_after_1am
  alias: "[LIGHTS - Living] Turn off after 1AM"
  trigger:
    - platform: time
      at: 01:00:00
  action:
    - service: light.turn_off
      entity_id: light.living_room

- id: lights_living_set_relax_scene_via_remote
  alias: "[LIGHTS - Living] Set Relax scene via remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room
        event: 3002 # right_upper_short_release
  action:
    service: scene.turn_on
    entity_id: scene.living_room_relax

- id: lights_living_turn_off_via_remote
  alias: "[LIGHTS - Living] Turn off via remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room
        event: 4002 # right_lower_short_release
  action:
    - service: light.turn_off
      entity_id: light.Living_room

- id: lights_office_set_circadian_lighting_via_remote
  alias: "[LIGHTS - Office] Turn on Circadian Lighting via remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: office
        event: 1002 # left_upper_short_release
  action:
    - service: script.activate_circadian_lighting
      data:
        circadian_lighting: switch.circadian_lighting_office
        light: light.office

- id: lights_office_set_relax_scene_via_remote
  alias: "[LIGHTS - Office] Set Relax scene via remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: office
        event: 2002 # left_lower_short_release
  action:
    service: scene.turn_on
    entity_id: scene.office_relax

- id: lights_office_set_green_scene_via_remote
  alias: "[LIGHTS - Office] Set Green scene via remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: office
        event: 3002 # right_upper_short_release
  action:
    service: scene.turn_on
    entity_id: scene.office_green

- id: lights_office_turn_off_via_remote
  alias: "[LIGHTS - Office] Turn off via remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: office
        event: 4002 # right_lower_short_release
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_office
    - service: light.turn_off
      entity_id: light.office

- id: lights_mancave_set_work_scene_via_remote
  alias: "[LIGHTS - Mancave] Set Work scene via remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: mancave
        event: 1002 # left_upper_short_release
  action:
    - service: script.activate_circadian_lighting
      data:
        circadian_lighting: switch.circadian_lighting_mancave
        light: light.mancave_lightstrip_1

- id: lights_mancave_set_relax_scene_via_remote
  alias: "[LIGHTS - Mancave] Set Relax scene via remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: mancave
        event: 2002 # left_lower_short_release
  action:
    service: scene.turn_on
    entity_id: scene.mancave_relax

- id: lights_mancave_set_game_scene_via_remote
  alias: "[LIGHTS - Mancave] Set Game scene via remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: mancave
        event: 3002 # right_upper_short_release
  action:
    service: scene.turn_on
    entity_id: scene.mancave_game

- id: lights_mancave_turn_off_via_remote
  alias: "[LIGHTS - Mancave] Turn off via remote"
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: mancave
        event: 4002 # right_lower_short_release
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_mancave
    - service: light.turn_off
      entity_id: light.mancave

- id: lan_device_status
  alias: "[LAN] Alert on critical device status"
  trigger:
    - platform: state
      entity_id:
        - device_tracker.modem
        - device_tracker.heimdallr_ap1
        - device_tracker.thor
        - device_tracker.hel
        - device_tracker.ring
        - device_tracker.ringchime
      to: "offline"
      for:
        minutes: 5
  action:
    - service: notify.philip
      data_template:
        title: "Device {{ trigger.to_state.name }} is"
        message: >
          '{{ trigger.to_state.state }}'

- id: lan_device_detected
  alias: "[LAN] Alert on detection of new devices"
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    - service: notify.philip
      data_template:
        title: New device detected
        message: >
          {{trigger.event.data.host_name}}
          ({{trigger.event.data.entity_id}})
          MAC: {{trigger.event.data.mac}}
