#### SYSTEM ####################################################################

- id: system_set_lovelace_theme_on_startup
  alias: "[SYSTEM] Set Lovelace theme on startup"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data:
        name: sundown

- id: system_renew_letsencrypt_certificate
  alias: "[SYSTEM] Renew Let's Encrypt certificate"
  trigger:
    - platform: time
      at: 00:00:00
  action:
    - service: hassio.addon_restart
      data:
        addon: core_letsencrypt

- id: system_take_weekly_snapshot
  alias: "[SYSTEM] Take weekly snapshot"
  trigger:
    - platform: time
      at: 02:00:00
  condition:
    - condition: time
      weekday:
        - sun
  action:
    - service: hassio.snapshot_full
      data_template:
        name: Backup_{{ now().strftime('%Y-%m-%d') }}

#### RING ######################################################################

- id: ring_download_last_video
  alias: "[RING] Download last video"
  trigger:
    - platform: template
      value_template:
        "{{ is_state_attr('sensor.voordeur_last_activity', 'recording_status',
        'ready') }}"
  action:
    - service: downloader.download_file
      data_template:
        url: "{{ state_attr('camera.voordeur', 'video_url') }}"
        subdir: "{{ state_attr('camera.voordeur', 'friendly_name') }}"
        filename: "{{ state_attr('camera.voordeur', 'friendly_name') }}"
