- id: system_set_theme
  alias: "[SYSTEM] Set Lovelace theme"
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - choose:
        - conditions: "{{ is_state('sun.sun', 'below_horizon')}}"
          sequence:
            - service: frontend.set_theme
              data:
                name: "Google Dark Theme"
      default:
        - service: frontend.set_theme
          data:
            name: "Google Light Theme"
- id: system_renew_letsencrypt_certificate
  alias: "[SYSTEM] Renew Let's Encrypt certificate"
  trigger:
    - platform: time
      at: 00:00:00
  action:
    - service: hassio.addon_restart
      data:
        addon: core_letsencrypt
- id: system_take_weekly_snapshot
  alias: "[SYSTEM] Take weekly snapshot"
  trigger:
    - platform: time
      at: 02:00:00
  condition:
    - condition: time
      weekday:
        - sun
  action:
    - service: hassio.snapshot_full
      data_template:
        name: Backup_{{ now().strftime('%Y-%m-%d') }}
- id: blinds_close_at_dusk
  alias: "[BLINDS] Close at dusk"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      below: -2.5
  condition:
    - condition: time
      after: "16:30:00"
      before: "23:00:00"
  action:
    - service: cover.close_cover
      entity_id: cover.dining_room
    - service: cover.close_cover
      entity_id: cover.living_room
- id: blinds_open_at_dawn
  alias: "[BLINDS] Open at dawn"
  trigger:
    - platform: sun
      event: sunrise
  condition:
    - condition: time
      before: "10:00:00"
  action:
    - service: cover.open_cover
      entity_id: cover.dining_room
    - service: cover.open_cover
      entity_id: cover.living_room
    - service: cover.open_cover
      entity_id: cover.kitchen
- id: blinds_open_via_living_remote
  alias: "[BLINDS] Open via Living remote"
  trigger:
    - device_id: 583ab48731694ab8b1056ae3c4325295
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_1
  action:
    - service: cover.open_cover
      entity_id: cover.dining_room
    - service: cover.open_cover
      entity_id: cover.living_room
    - service: cover.open_cover
      entity_id: cover.kitchen
  mode: single
- id: blinds_close_via_living_remote
  alias: "[BLINDS] Close via Living remote"
  trigger:
    - device_id: 583ab48731694ab8b1056ae3c4325295
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_2
  action:
    - service: cover.close_cover
      entity_id: cover.dining_room
    - service: cover.close_cover
      entity_id: cover.living_room
    - service: cover.close_cover
      entity_id: cover.kitchen
  mode: single
- id: blinds_stop_via_living_remote
  alias: "[BLINDS] Stop via Living remote"
  trigger:
    - device_id: 583ab48731694ab8b1056ae3c4325295
      domain: deconz
      platform: device
      type: remote_button_long_release
      subtype: button_1
    - device_id: 583ab48731694ab8b1056ae3c4325295
      domain: deconz
      platform: device
      type: remote_button_long_release
      subtype: button_2
  action:
    - service: cover.stop_cover
      entity_id: cover.dining_room
    - service: cover.stop_cover
      entity_id: cover.living_room
    - service: cover.stop_cover
      entity_id: cover.kitchen
  mode: single
- id: lights_living_turn_on_at_dusk
  alias: "[LIGHTS - Living] Turn on at dusk"
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      below: -1.0
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_relax
- id: lights_living_turn_off_after_1am
  alias: "[LIGHTS - Living] Turn off after 1AM"
  trigger:
    - platform: time
      at: 01:00:00
  action:
    - service: light.turn_off
      entity_id: light.living_room
- id: lights_living_set_relax_scene_via_remote
  alias: "[LIGHTS - Living] Set Relax scene via remote"
  trigger:
    - device_id: 583ab48731694ab8b1056ae3c4325295
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_3
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_relax
  mode: single
- id: lights_living_turn_off_via_remote
  alias: "[LIGHTS - Living] Turn off via remote"
  trigger:
    - device_id: 583ab48731694ab8b1056ae3c4325295
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_4
  action:
    - service: light.turn_off
      entity_id: light.living_room
  mode: single
- id: lights_office_set_work_scene_via_remote
  alias: "[LIGHTS - Office] Set Work scene via remote"
  trigger:
    - device_id: 7f235b29c5fe417c94497e1e3287a768
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_1
  action:
    - service: scene.turn_on
      entity_id: scene.office_work
  mode: single
- id: lights_office_set_relax_scene_via_remote
  alias: "[LIGHTS - Office] Set Relax scene via remote"
  trigger:
    - device_id: 7f235b29c5fe417c94497e1e3287a768
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_2
  action:
    - service: scene.turn_on
      entity_id: scene.office_relax
  mode: single
- id: lights_office_set_green_scene_via_remote
  alias: "[LIGHTS - Office] Set Green scene via remote"
  trigger:
    - device_id: 7f235b29c5fe417c94497e1e3287a768
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_3
  action:
    - service: scene.turn_on
      entity_id: scene.office_green
  mode: single
- id: lights_office_turn_off_via_remote
  alias: "[LIGHTS - Office] Turn off via remote"
  trigger:
    - device_id: 7f235b29c5fe417c94497e1e3287a768
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_4
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_office
    - service: light.turn_off
      entity_id: light.office
  mode: single
- id: lights_mancave_set_work_scene_via_remote
  alias: "[LIGHTS - Mancave] Set Work scene via remote"
  trigger:
    - device_id: ea252024782f4b98bf6c09f8456b245d
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_1
  action:
    - service: scene.turn_on
      entity_id: scene.mancave_work
  mode: single
- id: lights_mancave_set_relax_scene_via_remote
  alias: "[LIGHTS - Mancave] Set Relax scene via remote"
  trigger:
    - device_id: ea252024782f4b98bf6c09f8456b245d
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_2
  action:
    - service: scene.turn_on
      entity_id: scene.mancave_relax
  mode: single
- id: lights_mancave_set_game_scene_via_remote
  alias: "[LIGHTS - Mancave] Set Game scene via remote"
  trigger:
    - device_id: ea252024782f4b98bf6c09f8456b245d
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_3
  action:
    - service: scene.turn_on
      entity_id: scene.mancave_game
  mode: single
- id: lights_mancave_turn_off_via_remote
  alias: "[LIGHTS - Mancave] Turn off via remote"
  trigger:
    - device_id: ea252024782f4b98bf6c09f8456b245d
      domain: deconz
      platform: device
      type: remote_button_short_release
      subtype: button_4
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_mancave
    - service: light.turn_off
      entity_id: light.mancave
  mode: single
- id: lights_mancave_turn_off_after_1am
  alias: "[LIGHTS - Mancave] Turn off after 1AM"
  trigger:
    - platform: time
      at: 01:00:00
  action:
    - service: switch.turn_off
      entity_id: switch.circadian_lighting_mancave
    - service: light.turn_off
      entity_id: light.mancave
- id: lan_device_status
  alias: "[LAN] Alert on critical device status"
  trigger:
    - platform: state
      entity_id:
        - device_tracker.modem
        - device_tracker.heimdallr_ap1
        - device_tracker.thor
        - device_tracker.hel
        - device_tracker.ring
        - device_tracker.ringchime
      to: offline
      for:
        minutes: 5
  action:
    - service: notify.philip
      data_template:
        title: Device {{ trigger.to_state.name }} is {{ trigger.to_state.state }}
- id: lan_device_detected
  alias: "[LAN] Alert on detection of new devices"
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    - service: notify.philip
      data_template:
        title: New device detected
        message:
          "{{trigger.event.data.host_name}} ({{trigger.event.data.entity_id}})
          MAC: {{trigger.event.data.mac}}"
- id: "1609087690776"
  alias: "[LIGHTS - Christmas Tree] Turn on at 8:30 AM"
  trigger:
    - platform: time
      at: 08:30:00
  action:
    - service: switch.turn_on
      entity_id: switch.christmas_tree
