- alias: 'Lovelace: Set theme on startup'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data:
        name: sundown
       
- alias: "Let's Encrypt: Renew"
  trigger:
    - platform: time
      at: '00:00:00'
  action:
    - service: hassio.addon_restart
      data:
        addon: core_letsencrypt
 
##
# LIGTHS
##

- alias: 'Turn lights on as the sun gets dimmer'
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      below: 1.5
  action:
    - service: light.turn_on
      entity_id: light.living

- alias: 'Turn lights off after 1AM'
  trigger:
    - platform: time
      at: '01:00:00'
  action:
    - service: light.turn_off
      entity_id: light.living

##
# BLINDS
##

- alias: 'Close blinds at dusk'
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      below: -2.5
  action:
    - service: cover.close_cover
      entity_id: cover.living_achteraan
    - service: cover.close_cover
      entity_id: cover.living_vooraan

- alias: 'Open blinds at dawn'
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: cover.open_cover
      entity_id: cover.living_achteraan
    - service: cover.open_cover
      entity_id: cover.living_vooraan

##
# RING
##

# - alias: 'Ring: Download last video'
#   trigger:
#     - platform: template
#       value_template: '{{ is_state_attr(''sensor.voordeur_last_activity'',
#     ''recording_status'', ''ready'') }}'
#   action:
#     - service: downloader.download_file
#       data_template:
#         url: "{{ state_attr('camera.voordeur', 'video_url') }}"
#         subdir: "{{state_attr('camera.voordeur', 'friendly_name')}}"
#         filename: "{{state_attr('camera.voordeur', 'friendly_name')}}"
