#### CORE ######################################################################

default_config:
discovery:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
  # Add more dashboards
  dashboards:
    lovelace-generated:
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true

customizer:
  custom_ui: local

#### INCLUDES ##################################################################

automation: !include automations.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
