#### CORE ######################################################################

default_config:
discovery:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#### INCLUDES ##################################################################

automation: !include automations.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

#### UI  #######################################################################

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml
  resources: !include ui-lovelace-resources.yaml
  dashboards:
    lovelace-living:
      mode: yaml
      filename: ui-lovelace-living.yaml
      title: 01 Living
      icon: mdi:sofa
      show_in_sidebar: true
    lovelace-office:
      mode: yaml
      filename: ui-lovelace-office.yaml
      title: 02 Office
      icon: mdi:desk
      show_in_sidebar: true
    lovelace-theater:
      mode: yaml
      filename: ui-lovelace-theater.yaml
      title: 03 Theater
      icon: mdi:theater
      show_in_sidebar: true
    # lovelace-bedroom:
    #   mode: yaml
    #   filename: ui-lovelace-bedroom.yaml
    #   title: 04 Bedroom
    #   icon: mdi:bed-king
    #   show_in_sidebar: true
    lovelace-system:
      mode: yaml
      filename: ui-lovelace-system.yaml
      title: 05 System
      icon: mdi:server-network
      show_in_sidebar: true

customizer:
  custom_ui: local
