#### CORE ######################################################################

default_config:

homeassistant:
  name: Thuis
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  unit_system: metric
  time_zone: Europe/Brussels
  customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

hacs:
  token: !secret hacs_token
  appdaemon: true

customizer:
  custom_ui: local

#### INCLUDES ##################################################################

automation: !include automations.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml

#### INTEGRATIONS ##############################################################

discovery:

downloader:
  download_dir: downloads
