background: var(--background-image)
custom_header:
  background: rgba(155, 155, 155, 0.25)
  compact_mode: true
resources:
- type: module
  url: /community_plugin/custom-header/custom-header.js
- type: module
  url: /community_plugin/decluttering-card/decluttering-card.js
- type: js
  url: /community_plugin/bar-card/bar-card.js
- type: module
  url: /community_plugin/button-card/button-card.js
- type: module
  url: /community_plugin/lovelace-auto-entities/auto-entities.js
- type: module
  url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
- type: module
  url: /community_plugin/mini-media-player/mini-media-player-bundle.js
- type: module
  url: /community_plugin/simple-weather-card/simple-weather-card-bundle.js
- type: module
  url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
- type: module
  url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
- type: js
  url: /community_plugin/light-entity-card/light-entity-card.js
- type: js
  url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
title: Thuis
views:
- badges:
  - entity: person.philip
  - entity: person.elke
  - entity: sun.sun
  cards:
  - entity: weather.thuis
    name: Weer
    type: custom:simple-weather-card
  - artwork: cover
    entity: media_player.spotify
    hide:
      power: true
      source: false
      volume: true
    icon: mdi:spotify
    type: custom:mini-media-player
  - entities:
    - entities:
      - light.vloerlamp
      - light.plantenbak
      - light.kerstboom
      - light.oosterse_lamp
      head:
        entity: light.living
        icon: mdi:sofa
        name: Living
        type: custom:slider-entity-row
      type: custom:fold-entity-row
    - entities:
      - entity: light.hue_lightstrip_plus_1
        name: LED Strip
      - entity: light.ikea_ps_2017
      - entity: switch.circadian_lighting_circadian_lighting
      head:
        entity: light.bureau
        icon: mdi:desk
        name: Bureau
        type: custom:slider-entity-row
      type: custom:fold-entity-row
    - entities:
      - entity: light.cinema_2
        name: Spots
      - entity: light.hue_iris_1
        name: Hue Iris
      head:
        entity: light.cinema
        icon: mdi:theater
        name: Cinema
        type: custom:slider-entity-row
      type: custom:fold-entity-row
    - entities:
      - light.bolletjes
      - light.nachtlamp_elke
      - light.nachtlamp_philip
      head:
        entity: light.slaapkamer
        icon: mdi:bed-king
        name: Slaapkamer
        type: custom:slider-entity-row
      type: custom:fold-entity-row
    - entities:
      - entity: light.nachtlamp_xander
        name: Nachtlamp
      head:
        entity: light.kinderkamer
        icon: mdi:baby-bottle
        name: Xander
        type: custom:slider-entity-row
      type: custom:fold-entity-row
    show_header_toggle: false
    title: Licht
    type: entities
  - entities:
    - entity: cover.keuken
    - entity: cover.living_achteraan
    - entity: cover.living_vooraan
    show_header_toggle: false
    title: Rolluiken
    type: entities
  - entity: camera.voordeur
    type: picture-entity
  icon: mdi:home
  path: default_view
  title: ''
- badges: []
  cards:
  - artwork: cover
    entity: media_player.living
    hide:
      power: true
      source: false
      volume: false
    icon: mdi:cast
    type: custom:mini-media-player
  - entities:
    - entity: remote.living
      name: Harmony
    show_header_toggle: false
    type: entities
  - entities:
    - entity: light.vloerlamp
    - entity: light.plantenbak
    - entity: light.oosterse_lamp
    show_header_toggle: true
    title: Lichten
    type: entities
  - brightness: true
    brightness_icon: weather-sunny
    color_picker: true
    color_temp: true
    color_wheel: true
    effects_list: true
    entity: light.living
    full_width_sliders: true
    group: false
    header: Living
    persist_features: false
    show_slider_percent: true
    smooth_color_wheel: false
    temperature_icon: thermometer
    type: custom:light-entity-card
    white_icon: file-word-box
    white_value: true
  icon: mdi:sofa
  path: living
  title: Living
- badges: []
  cards:
  - artwork: cover
    entity: media_player.bureau
    hide:
      power: true
      source: false
      volume: false
    icon: mdi:play-circle
    name: Sonos
    type: custom:mini-media-player
  - entities:
    - entity: sensor.samsung_m2020_series_192_168_5_120_toner_black
      name: Printer Toner
    type: entities
  - entities:
    - entity: light.bureau
      name: Alle Lichten
    - entity: light.hue_lightstrip_plus_1
      name: LED Strip
    - entity: light.ikea_ps_2017
    show_header_toggle: false
    type: entities
  icon: mdi:desk
  path: bureau
  title: Bureau
- badges: []
  cards:
  - artwork: cover
    entity: media_player.cinema
    hide:
      power: true
      source: false
      volume: false
    icon: mdi:cast
    type: custom:mini-media-player
  - entities:
    - entity: remote.home_theater
      name: Harmony
    show_header_toggle: false
    type: entities
  - entities:
    - entity: light.cinema_2
      name: Spots
    - entity: light.hue_iris_1
      name: Hue Iris
    show_header_toggle: true
    title: Lichten
    type: entities
  icon: mdi:theater
  path: cinema
  title: Cinema
- badges: []
  cards:
  - entities:
    - entity: light.slaapkamer
      name: Alle Lichten
    - entity: light.bolletjes
    - entity: light.nachtlamp_elke
    - entity: light.nachtlamp_philip
    show_header_toggle: false
    type: entities
  icon: mdi:bed-king
  path: slaapkamer
  title: Slaapkamer
- badges: []
  cards:
  - entities:
    - entity: light.nachtlamp_xander
      name: Nachtlamp
    show_header_toggle: false
    type: entities
  icon: mdi:bed-single
  path: xander
  title: Xander
- badges: []
  cards:
  - artwork: cover
    entity: media_player.badkamer
    hide:
      power: true
      source: false
      volume: false
    icon: mdi:play-circle
    name: Sonos
    type: custom:mini-media-player
  icon: mdi:shower
  path: badkamer
  title: Badkamer
- badges: []
  cards:
  - cards:
    - entities:
      - entity: switch.pihole_toggle
        icon: mdi:pi-hole
      type: entities
    - cards:
      - cards:
        - entities:
          - sensor.pi_hole_ads_blocked_today
          hour24: true
          hours_to_show: 24
          name: Ads Blocked
          show:
            graph: line
          type: custom:mini-graph-card
        - entities:
          - sensor.pi_hole_ads_percentage_blocked_today
          hour24: true
          hours_to_show: 24
          name: Percentage Blocked
          show:
            graph: line
          type: custom:mini-graph-card
        type: horizontal-stack
      - cards:
        - entities:
          - sensor.pi_hole_dns_unique_clients
          hour24: true
          hours_to_show: 24
          name: Clients
          show:
            graph: none
          type: custom:mini-graph-card
        type: horizontal-stack
      type: vertical-stack
    title: Pi-Hole
    type: custom:vertical-stack-in-card
  - cards:
    - cards:
      - entities:
        - sensor.processor_use
        hours_to_show: 24
        icon: mdi:cpu-64-bit
        line_color: '#389638'
        name: CPU
        type: custom:mini-graph-card
      - align: split
        color: '#2980b9'
        entity: sensor.memory_use_percent
        icon: mdi:memory
        icon_position: inside
        title: RAM
        title_position: inside
        type: custom:bar-card
      - align: split
        color: '#2980b9'
        entity: sensor.disk_use_percent
        icon: mdi:harddisk
        icon_position: inside
        title: HDD
        title_position: inside
        type: custom:bar-card
      title: Hel
      type: custom:vertical-stack-in-card
    - cards:
      - entities:
        - sensor.mikrotik_cpu_load
        hours_to_show: 24
        icon: mdi:cpu-32-bit
        line_color: '#389638'
        name: CPU
        type: custom:mini-graph-card
      - align: split
        color: '#2980b9'
        entity: sensor.mikrotik_memory_usage
        icon: mdi:memory
        icon_position: inside
        title: RAM
        title_position: inside
        type: custom:bar-card
      - align: split
        color: '#2980b9'
        entity: sensor.mikrotik_hdd_usage
        icon: mdi:harddisk
        icon_position: inside
        title: HDD
        title_position: inside
        type: custom:bar-card
      title: Heimdallr
      type: custom:vertical-stack-in-card
    type: vertical-stack
  - cards:
    - entities:
      - sensor.speedtest_download
      hours_to_show: 24
      icon: mdi:download-network
      line_color: '#2980b9'
      line_width: 6
      name: Download
      type: custom:mini-graph-card
    - entities:
      - sensor.speedtest_upload
      hours_to_show: 24
      icon: mdi:upload-network
      line_color: '#2980b9'
      line_width: 6
      name: Upload
      type: custom:mini-graph-card
    - entities:
      - sensor.speedtest_ping
      hours_to_show: 24
      icon: mdi:server-network
      line_color: '#2980b9'
      line_width: 6
      name: Ping
      type: custom:mini-graph-card
    type: horizontal-stack
  - cards:
    - entities:
      - entity: sensor.wireguard_freyja_tx
        name: Freyja
      - entity: sensor.wireguard_loki_tx
        name: Loki
      - entity: sensor.wireguard_fenrir_tx
        name: Fenrir
      icon: mdi:vpn
      name: Data Transfered
      show:
        graph: line
      type: custom:mini-graph-card
    - entities:
      - entity: sensor.wireguard_freyja_latest_handshake
        name: Freyja
      - entity: sensor.wireguard_loki_latest_handshake
        name: Loki
      - entity: sensor.wireguard_fenrir_latest_handshake
        name: Fenrir
      show_header_toggle: false
      type: entities
    title: WireGuard
    type: custom:vertical-stack-in-card
  icon: mdi:server-network
  path: lan
  title: LAN
- badges:
  - entity: sensor.plex_living
  cards:
  - entities:
    - entity: sensor.ophaalkalender_restafval
      name: Restafval
    - entity: sensor.ophaalkalender_papier
      name: Papier
    - entity: sensor.ophaalkalender_pmd
      name: P+MD
    type: entities
  - entities:
    - entity: device_tracker.hd1913
    - entity: device_tracker.loki
    - entity: device_tracker.iphone_van_elke
    show_header_toggle: false
    title: Devices
    type: entities
  icon: ''
  path: misc
  title: Misc
