custom_header:
  # background: "rgba(155, 155, 155, 0.25)"
  compact_mode: true
  hidden_tab_redirect: false
  hide_config: true
  hide_help: true
  hide_unused: true
title: System
views:
  - !include lovelace/views/99-system.yaml
