background: var(--background-image)
custom_header:
  background: "rgba(155, 155, 155, 0.25)"
  compact_mode: true
  hidden_tab_redirect: false
  hide_tabs:
    - test
  hide_config: true
  hide_help: true
  hide_unused: false
resources: !include lovelace/resources.yaml
title: Thuis
views:
  - !include lovelace/views/01-home.yaml
  - !include lovelace/views/02-living.yaml
  - !include lovelace/views/03-office.yaml
  - !include lovelace/views/04-theater.yaml
  - !include lovelace/views/05-bedroom.yaml
  - !include lovelace/views/06-kidsroom.yaml
  - !include lovelace/views/07-bathroom.yaml
  - !include lovelace/views/08-lan.yaml
  - !include lovelace/views/99-test.yaml
