title: Automations
icon: mdi:robot
path: automations
cards:
  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      show_header_toggle: false
      title: Lights
    filter:
      include:
        - entity_id: "automation.lights*"
          options:
            secondary_info: last-changed

  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      show_header_toggle: false
      title: Blinds
    filter:
      include:
        - entity_id: "automation.blinds*"
          options:
            secondary_info: last-changed

  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      show_header_toggle: false
      title: LAN
    filter:
      include:
        - entity_id: "automation.lan*"
          options:
            secondary_info: last-changed

  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      show_header_toggle: false
      title: System
    filter:
      include:
        - entity_id: "automation.system*"
          options:
            secondary_info: last-changed

  - type: custom:auto-entities
    show_empty: false
    card:
      type: entities
      show_header_toggle: false
      title: Alerts
    filter:
      include:
        - entity_id: "alert.*"
          options:
            secondary_info: last-changed
