#### CUSTOMIZE #################################################################

homeassistant:
  customize:
    light.bedroom:
      friendly_name: Slaapkamer
      icon: mdi:bed-king
    light.bedroom_elke:
      friendly_name: Slaapkamer (Elke)
      icon: mdi:human-female
    light.bedroom_philip:
      friendly_name: Slaapkamer (Philip)
      icon: mdi:human-male
    light.night_light_elke:
      friendly_name: Nachtlamp Elke
      icon: mdi:lamp
    light.night_light_philip:
      friendly_name: Nachtlamp Philip
      icon: mdi:lamp
    switch.bedroom_string_lights:
      friendly_name: Bolletjes
      icon: mdi:string-lights

#### AUTOMATIONS ###############################################################

## deCONZ events
# 1XXX  Button #1 up to #8
# XXX1  Button hold
# XXX2  Button short release
# XXX3  Button long release

automation:
  - id: lights_bedroom_philip_turn_on_via_remote
    alias: "[LIGHTS - Bedroom] Turn Philip's lights on via dimmer"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_philip
          event: 1002
    action:
      - service: light.turn_on
        entity_id: light.bedroom_philip

  - id: lights_bedroom_philip_increase_brightness_via_remote
    alias: "[LIGHTS - Bedroom] Increase brightness of Philip's lights via dimmer"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_philip
          event: 2002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_philip
          brightness: >
            {% set bri = state_attr('light.bedroom_philip', 'brightness') | int %}
            {{ [bri+30, 249] | min }}

  - id: lights_bedroom_philip_decrease_brightness_via_remote
    alias: "[LIGHTS - Bedroom] Decrease brightness of Philip's lights via dimmer"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_philip
          event: 3002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_philip
          brightness: >
            {% set bri = state_attr('light.bedroom_philip', 'brightness') | int %}
            {{ [bri-30, 0] | max }}

  - id: lights_bedroom_philip_turn_off_via_remote
    alias: "[LIGHTS - Bedroom] Turn Philip's lights off via dimmer"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_philip
          event: 4002
    action:
      - service: light.turn_off
        entity_id: light.bedroom_philip

  ###

  - id: lights_bedroom_elke_turn_on_via_remote
    alias: "[LIGHTS - Bedroom] Turn Elke's lights on via dimmer"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_elke
          event: 1002
    action:
      - service: light.turn_on
        entity_id: light.bedroom_elke

  - id: lights_bedroom_elke_increase_brightness_via_remote
    alias: "[LIGHTS - Bedroom] Increase brightness of Elke's lights via dimmer"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_elke
          event: 2002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_elke
          brightness: >
            {% set bri = state_attr('light.bedroom_elke', 'brightness') | int %}
            {{ [bri+30, 249] | min }}

  - id: lights_bedroom_elke_decrease_brightness_via_remote
    alias: "[LIGHTS - Bedroom] Decrease brightness of Elke's lights via dimmer"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_elke
          event: 3002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_elke
          brightness: >
            {% set bri = state_attr('light.bedroom_elke', 'brightness') | int %}
            {{ [bri-30, 0] | max }}

  - id: lights_bedroom_elke_turn_off_via_remote
    alias: "[LIGHTS - Bedroom] Turn Elke's lights off via dimmer"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: bedroom_elke
          event: 4002
    action:
      - service: light.turn_off
        entity_id: light.bedroom_elke
