cover:
  - platform: rfxtrx
    automatic_add: False
    devices:
      071a000001020300: # RFY SOMFY
        name: Living front
      071a000001020301: # RFY SOMFY
        name: Living back
      071a000001020302: # RFY SOMFY
        name: Kitchen

#### CUSTOMIZE #################################################################

homeassistant:
  customize:
    cover.living_back:
      friendly_name: Living achteraan
    cover.living_front:
      friendly_name: Living vooraan
    cover.kitchen:
      friendly_name: Keuken

#### AUTOMATIONS ###############################################################

automation:
  - id: blinds_close_at_dusk
    alias: "[BLINDS] Close at dusk"
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: -3
    condition:
      - condition: time
        after: "16:30:00"
        before: "23:00:00"
    action:
      - service: cover.close_cover
        entity_id: cover.living_back
      - service: cover.close_cover
        entity_id: cover.living_front

  - id: blinds_open_at_dawn
    alias: "[BLINDS] Open at dawn"
    trigger:
      - platform: sun
        event: sunrise
    condition:
      - condition: time
        before: "10:00:00"
    action:
      - service: cover.open_cover
        entity_id: cover.living_back
      - service: cover.open_cover
        entity_id: cover.living_front
      - service: cover.open_cover
        entity_id: cover.kitchen
