#### INTEGRATIONS ##############################################################

speedtestdotnet:
  scan_interval:
    minutes: 120

#### CUSTOMIZE #################################################################

homeassistant:
  customize_glob:
    device_tracker.*:
      templates:
        icon_color: >
          if (state === 'home') return 'white';
          else return 'rgb(225, 75, 76)';

#### GROUPS ####################################################################

group:
  device_58z72z2:
    name: 58Z72Z2
    icon: mdi:laptop-windows
    entities:
      - device_tracker.58z72z2
      - device_tracker.58z72z2_2
  device_fenrir:
    name: Fenrir
    icon: mdi:laptop-windows
    entities:
      - device_tracker.fenrir
      - device_tracker.fenrir_2

sensor:
  #### SERVER MONITORING #######################################################

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: "/"
      - type: memory_use_percent
      - type: processor_use

  #### COUNT ENTITIES ##########################################################

  - platform: template
    sensors:
      count_automations:
        friendly_name: Automations
        icon_template: mdi:robot
        value_template: "{{ states.automation | count }}"
      count_binary_sensors:
        friendly_name: Binary Sensors
        icon_template: mdi:contrast-circle
        value_template: "{{ states.binary_sensor | count }}"
      count_device_trackers:
        friendly_name: Device Trackers
        icon_template: mdi:radar
        value_template: "{{ states.device_tracker | count }}"
      count_lights:
        friendly_name: Lights
        icon_template: mdi:lightbulb-group
        value_template: "{{ states.light | count }}"
      count_scripts:
        friendly_name: Scripts
        icon_template: mdi:script-text
        value_template: "{{ states.script | count }}"
      count_sensors:
        friendly_name: Sensors
        icon_template: mdi:leak
        value_template: "{{ states.sensor | count }}"
      count_switches:
        friendly_name: Switches
        icon_template: mdi:light-switch
        value_template: "{{ states.switch | count }}"
      count_zones:
        friendly_name: Zones
        icon_template: mdi:map-marker-radius
        value_template: "{{ states.zone | count }}"

  #### WIREGUARD ###############################################################

  - platform: rest
    resource: http://a0d7b954-wireguard
    name: wireguard_sensor
    value_template: TEST
    json_attributes:
      - Loki
      - Freyja
      - Fenrir
  - platform: template
    sensors:
      wireguard_loki_latest_handshake:
        friendly_name: Loki latest handshak
        icon_template: mdi:handshake
        unit_of_measurement: s
        value_template: "{{ states.sensor.wireguard_sensor.attributes['Loki']['latest_handshake'] }}"
      wireguard_freyja_latest_handshake:
        friendly_name: Freyja latest handshake
        icon_template: mdi:handshake
        unit_of_measurement: s
        value_template: "{{ states.sensor.wireguard_sensor.attributes['Freyja']['latest_handshake'] }}"
      wireguard_fenrir_latest_handshake:
        friendly_name: Fenrir latest handshake
        icon_template: mdi:handshake
        unit_of_measurement: s
        value_template: "{{ states.sensor.wireguard_sensor.attributes['Fenrir']['latest_handshake'] }}"

#### AUTOMATIONS ###############################################################

automation:
  - id: lan_device_status
    alias: "[LAN] Alert on critical device status"
    trigger:
      - platform: state
        entity_id:
          - device_tracker.modem
          - device_tracker.heimdallr_ap1
          - device_tracker.thor
          - device_tracker.hel
          - device_tracker.sec84251979ca6b
          - device_tracker.ring
          - device_tracker.ringchime
          # - device_tracker.living
          - device_tracker.living_harmony
          - device_tracker.avr_x6200w
          # - device_tracker.cinema
          # - device_tracker.ubp_x800
          - device_tracker.cinema_harmony
          - device_tracker.sonos_connect
          - device_tracker.sonos_play1
          # - device_tracker.ps4pro
          # - device_tracker.nintendoswitch
        to: "offline"
        for:
          minutes: 5
    action:
      - service: notify.philip
        data_template:
          title: "Device {{ trigger.to_state.name }} is"
          message: >
            '{{ trigger.to_state.state }}'

  - id: lan_device_detected
    alias: "[LAN] Alert on detection of new devices"
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.philip
        data_template:
          title: New device detected
          message: >
            {{trigger.event.data.host_name}}
            ({{trigger.event.data.entity_id}})
            MAC: {{trigger.event.data.mac}}
