homeassistant:
  customize:
    ## Hue rooms/zones
    light.beneden:
      icon: mdi:home-floor-0
    light.boven:
      icon: mdi:home-floor-1
    light.bureau:
      icon: mdi:lightbulb-group
    light.cinema:
      icon: mdi:lightbulb-group
    light.kinderkamer:
      icon: mdi:lightbulb-group
    light.living:
      icon: mdi:lightbulb-group
    light.slaapkamer:
      icon: mdi:lightbulb-group
    light.slaapkamer_elke:
      icon: mdi:lightbulb-group
    light.slaapkamer_philip:
      icon: mdi:lightbulb-group
    light.zolder:
      icon: mdi:home-floor-2
    ## Single lights
    light.cinema_spots:
      icon: mdi:wall-sconce-flat
    light.bolletjes:
      icon: mdi:string-lights
    light.iris_1:
      icon: mdi:lamp
    light.lightstrip_1:
      icon: mdi:led-strip-variant
    light.lightstrip_2:
      icon: mdi:led-strip-variant
    light.ikea_ps_2017:
      icon: mdi:lamp
    light.kerstboom:
      icon: mdi:pine-tree
    light.nachtlamp_elke:
      icon: mdi:lamp
    light.nachtlamp_philip:
      icon: mdi:lamp
    light.nachtlamp_xander:
      icon: mdi:lamp
    light.oosterse_lamp:
      icon: mdi:floor-lamp-variant
    light.plantenzuil:
      icon: mdi:floor-lamp-variant
    light.vloerlamp:
      icon: mdi:floor-lamp
    ## Light groups
    light.living_lights:
      friendly_name: Living
      icon: mdi:lightbulb-group
    light.office_lights:
      friendly_name: Bureau
      icon: mdi:lightbulb-group
    light.theater_lights:
      friendly_name: Cinema
      icon: mdi:lightbulb-group
    light.bedroom_lights:
      friendly_name: Slaapkamer
      icon: mdi:lightbulb-group
    light.kidsroom_lights:
      friendly_name: Kinderkamer
      icon: mdi:lightbulb-group
    light.downstairs_lights:
      friendly_name: Beneden
      icon: mdi:lightbulb-group
    light.upstairs_lights:
      friendly_name: Boven
      icon: mdi:lightbulb-group
    light.attic_lights:
      friendly_name: Zolder
      icon: mdi:lightbulb-group

light:
  - platform: group
    name: Living Lights
    entities:
      - light.oosterse_lamp
      - light.plantenzuil
      - light.vloerlamp
  - platform: group
    name: Office Lights
    entities:
      - light.ikea_ps_2017
      - light.lightstrip_1
      - light.lightstrip_2
  - platform: group
    name: Theater Lights
    entities:
      - light.cinema_spots
      - light.iris_1
  - platform: group
    name: Bedroom Lights
    entities:
      - light.bolletjes
      - light.nachtlamp_elke
      - light.nachtlamp_philip
  - platform: group
    name: Kids' Room Lights
    entities:
      - light.nachtlamp_xander

  - platform: group
    name: Downstairs Lights
    entities:
      - light.oosterse_lamp
      - light.plantenzuil
      - light.vloerlamp
  - platform: group
    name: Upstairs Lights
    entities:
      - light.cinema_spots
      - light.iris_1
      - light.nachtlamp_xander
  - platform: group
    name: Attic Lights
    entities:
      - light.ikea_ps_2017
      - light.lightstrip_1
      - light.lightstrip_2
      - light.bolletjes
      - light.nachtlamp_elke
      - light.nachtlamp_philip
