#### CUSTOMIZE #################################################################

homeassistant:
  customize:
    light.kids_room:
      friendly_name: Kinderkamer
      icon: mdi:baby
    light.night_light_xander:
      friendly_name: Nachtlamp Xander
      icon: mdi:lamp

    light.downstairs:
      friendly_name: Beneden
      icon: mdi:home-floor-g
    light.upstairs:
      friendly_name: Boven
      icon: mdi:home-floor-1
    light.attic:
      friendly_name: Zolder
      icon: mdi:home-floor-2

#### GROUPS ####################################################################

light:
  - platform: group
    name: Downstairs
    entities:
      - light.living
  - platform: group
    name: Upstairs
    entities:
      - light.kids_room
      - light.theater
  - platform: group
    name: Attic
    entities:
      - light.bedroom
      - light.office
