#### CUSTOMIZE #################################################################

homeassistant:
  customize:
    light.living:
      friendly_name: Living
      icon: mdi:sofa
    light.living_eastern_lamp:
      friendly_name: Oosterse lamp
      icon: mdi:floor-lamp-variant
    light.Living_plant_lamp:
      friendly_name: Plantenzuil
      icon: mdi:floor-lamp-variant
    switch.living_floor_lamp:
      friendly_name: Vloerlamp
      icon: mdi:floor-lamp

#### CIRCADIAN LIGHTING ########################################################

switch:
  - platform: circadian_lighting
    name: Living
    lights_xy:
      - light.living

#### SCENES ####################################################################

scene:
  - name: Living Relax
    # icon: mdi:foo
    entities:
      light.living:
        state: on
        brightness: 200
        color_temp: 447
        # kelvin: 2700
        hs_color: [36.568, 66.275]
  - name: Living Romantic
    # icon: mdi:foo
    entities:
      light.living:
        state: on
        brightness: 128
        kelvin: 1800

#### AUTOMATIONS ###############################################################

automation:
  - id: lights_turn_on_at_sunset
    alias: "[LIGHTS - Living] Turn on as the sun goes down"
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: 1.5
    action:
      - service: script.activate_scene
        data:
          circadian_lighting: switch.circadian_lighting_living
          scene: scene.living_relax

  - id: lights_turn_off_after_1am
    alias: "[LIGHTS - Living] Turn off after 1AM"
    trigger:
      - platform: time
        at: 01:00:00
    action:
      - service: light.turn_off
        entity_id: light.living
