#### CUSTOMIZE #################################################################

homeassistant:
  customize:
    light.living:
      friendly_name: Living
      icon: mdi:sofa
    light.living_eastern_lamp:
      friendly_name: Oosterse lamp
      icon: mdi:floor-lamp-variant
    light.Living_plant_lamp:
      friendly_name: Plantenzuil
      icon: mdi:floor-lamp-variant
    switch.living_floor_lamp:
      friendly_name: Vloerlamp
      icon: mdi:floor-lamp

#### CIRCADIAN LIGHTING ########################################################

switch:
  - platform: circadian_lighting
    name: Living
    lights_xy:
      - light.living

#### SCENES ####################################################################

scene:
  - name: Living Relax
    icon: mdi:palette-swatch
    entities:
      light.living:
        state: on
        brightness: 200
        color_temp: 447
        hs_color: [36.568, 66.275]
  - name: Living Romantic
    icon: mdi:palette-swatch
    entities:
      light.living:
        state: on
        brightness: 128
        kelvin: 1800

#### AUTOMATIONS ###############################################################

automation:
  - id: lights_turn_on_at_sunset
    alias: "[LIGHTS - Living] Turn on as the sun goes down"
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: -1.0
    action:
      - service: script.activate_scene
        data:
          circadian_lighting: switch.circadian_lighting_living
          scene: scene.living_relax

  - id: lights_turn_off_after_1am
    alias: "[LIGHTS - Living] Turn off after 1AM"
    trigger:
      - platform: time
        at: 01:00:00
    action:
      - service: light.turn_off
        entity_id: light.living

  ## deCONZ events
  # 1XXX  Button #1 up to #8
  # XXX1  Button hold
  # XXX2  Button short release
  # XXX3  Button long release

  - id: lights_living_set_circadian_lighting_via_remote
    alias: "[LIGHTS - Living] Turn on Circadian Lighting via remote"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: living
          event: 1002 # left_upper_short_release
    action:
      - service: script.activate_circadian_lighting
        data:
          circadian_lighting: switch.circadian_lighting_living
          light: light.Living

  - id: lights_living_set_relax_scene_via_remote
    alias: "[LIGHTS - Living] Set Relax scene via remote"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: living
          event: 2002 # left_lower_short_release
    action:
      - service: script.activate_scene
        data:
          circadian_lighting: switch.circadian_lighting_living
          scene: scene.Living_relax

  - id: lights_living_set_romantic_scene_via_remote
    alias: "[LIGHTS - Living] Set Romantic scene via remote"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: living
          event: 3002 # right_upper_short_release
    action:
      - service: script.activate_scene
        data:
          circadian_lighting: switch.circadian_lighting_living
          scene: scene.Living_romantic

  - id: lights_living_turn_off_via_remote
    alias: "[LIGHTS - Living] Turn off via remote"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: living
          event: 4002 # right_lower_short_release
    action:
      - service: switch.turn_off
        entity_id: switch.circadian_lighting_living
      - service: light.turn_off
        entity_id: light.Living
