logger:
  default: info

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 30
  purge_interval: 1
  exclude:
    domains:
      - alert
      - calendar
      - camera
      - sun
      - updater
      - weblink
    entities:
      - binary_sensor.updater
      - sensor.date
      - sensor.time
      - sensor.last_boot
      - sensor.current_version
      - sensor.version_available

# influxdb:
#   host: a0d7b954-influxdb
#   port: 8086
#   database: homeassistant
#   username: !secret influxdb_username
#   password: !secret influxdb_password
#   max_retries: 3
#   default_measurement: state
