spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

webostv:
  host: !secret mancave_tv_ip
  name: Mancave TV

sensor:
  - platform: template
    sensors:
      living_harmony:
        value_template: "{{ state_attr('remote.living_room', 'current_activity') }}"
        friendly_name: "Living Activity"
      theater_harmony:
        value_template: "{{ state_attr('remote.home_theater', 'current_activity') }}"
        friendly_name: "Theater Activity"

switch:
  - platform: template
    switches:
      ## LIVING
      living_harmony_listen_to_music:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Listen to Music') }}"
        icon_template: mdi:music
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: "Listen to Music"
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: "PowerOff"
      living_harmony_watch_tv:
        value_template: "{{ is_state_attr('remote.living_room', 'current_activity', 'Watch TV') }}"
        icon_template: mdi:youtube-tv
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: "Watch TV"
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.living_room
            activity: "PowerOff"
      ## Mancave
      theater_harmony_watch_a_movie:
        value_template: "{{ is_state_attr('remote.home_theater', 'current_activity', 'Watch a Movie') }}"
        icon_template: mdi:movie-roll
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.home_theater
            activity: "Watch a Movie"
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.home_theater
            activity: "PowerOff"
      theater_harmony_watch_tv:
        value_template: "{{ is_state_attr('remote.home_theater', 'current_activity', 'Watch TV') }}"
        icon_template: mdi:youtube-tv
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.home_theater
            activity: "Watch TV"
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.home_theater
            activity: "PowerOff"
      theater_harmony_play_a_game:
        value_template: "{{ is_state_attr('remote.home_theater', 'current_activity', 'Play a Game') }}"
        icon_template: mdi:controller-classic
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.home_theater
            activity: "Play a Game"
        turn_off:
          service: remote.turn_on
          data:
            entity_id: remote.home_theater
            activity: "PowerOff"

script:
  ## LIVING
  living_harmony_volume_up:
    alias: Living Volume Up
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.living_room
          command: VolumeUp
          device: Soundbar
          num_repeats: 5
          delay_secs: 0.25
  living_harmony_volume_down:
    alias: Living Volume Down
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.living_room
          command: VolumeDown
          device: Soundbar
          num_repeats: 5
          delay_secs: 0.25
  living_harmony_mute:
    alias: Living Mute
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.living_room
          command: Mute
          device: Soundbar
  ## mancave
  theater_harmony_volume_up:
    alias: Living Volume Up
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.home_theater
          command: VolumeUp
          device: Receiver
          num_repeats: 5
          delay_secs: 0.25
  theater_harmony_volume_down:
    alias: Living Volume Down
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.home_theater
          command: VolumeDown
          device: Receiver
          num_repeats: 5
          delay_secs: 0.25
  theater_harmony_mute:
    alias: Living Mute
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.home_theater
          command: Mute
          device: Receiver
