#### CUSTOMIZE #################################################################

homeassistant:
  customize:
    light.office:
      friendly_name: Bureau
      icon: mdi:desk
    light.office_lightstrip_1:
      friendly_name: LED-strip 1
      icon: mdi:led-strip-variant
    light.office_lightstrip_2:
      friendly_name: LED-strip 2
      icon: mdi:led-strip-variant
    light.office_ikea_ps_2017:
      friendly_name: IKEA PS 2017
      icon: mdi:lamp

#### CIRCADIAN LIGHTING ########################################################

switch:
  - platform: circadian_lighting
    name: Office
    lights_xy:
      - light.office

#### SCENES ####################################################################

scene:
  - name: Office Green
    icon: mdi:palette-swatch
    entities:
      light.office:
        state: "on"
        brightness: 227
        color_temp: 301
        hs_color: [140.455, 58.627]
  - name: Office Relax
    icon: mdi:palette-swatch
    entities:
      light.office:
        state: "on"
        brightness: 144
        color_temp: 447
        hs_color: [36.568, 66.275]
  - name: Office Savannah Sunset
    icon: mdi:palette-swatch
    entities:
      light.office:
        state: "on"
        brightness: 200
        color_temp: 382
        hs_color: [16.925, 78.431]

#### AUTOMATIONS ###############################################################

## deCONZ events
# 1XXX  Button #1 up to #8
# XXX1  Button hold
# XXX2  Button short release
# XXX3  Button long release

automation:
  - id: lights_office_set_circadian_lighting_via_remote
    alias: "[LIGHTS - Office] Turn on Circadian Lighting via remote"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: office
          event: 1002 # left_upper_short_release
    action:
      - service: script.activate_circadian_lighting
        data:
          circadian_lighting: switch.circadian_lighting_office
          light: light.office

  - id: lights_office_set_relax_scene_via_remote
    alias: "[LIGHTS - Office] Set Relax scene via remote"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: office
          event: 2002 # left_lower_short_release
    action:
      - service: script.activate_scene
        data:
          circadian_lighting: switch.circadian_lighting_office
          scene: scene.office_relax

  - id: lights_office_set_green_scene_via_remote
    alias: "[LIGHTS - Office] Set Green scene via remote"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: office
          event: 3002 # right_upper_short_release
    action:
      - service: script.activate_scene
        data:
          circadian_lighting: switch.circadian_lighting_office
          scene: scene.office_green

  - id: lights_office_turn_off_via_remote
    alias: "[LIGHTS - Office] Turn off via remote"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: office
          event: 4002 # right_lower_short_release
    action:
      - service: switch.turn_off
        entity_id: switch.circadian_lighting_office
      - service: light.turn_off
        entity_id: light.office
