automation:
  - id: ring_download_last_video
    alias: "[RING] Download last video"
    trigger:
      - platform: template
        value_template:
          "{{ is_state_attr('sensor.voordeur_last_activity', 'recording_status',
          'ready') }}"
      # - platform: state
      #   entity_id: sensor.ringvideourl
    action:
      - service: downloader.download_file
        data_template:
          url: "{{ state_attr('camera.voordeur', 'video_url') }}"
          subdir: "{{ state_attr('camera.voordeur', 'friendly_name').lower().replace(' ', '_') }}"
          filename: "{{ state_attr('camera.voordeur', 'friendly_name').lower().replace(' ', '_') + 'mp4' }}"
          overwrite: true
