#### CUSTOMIZE #################################################################

homeassistant:
  customize_glob:
    device_tracker.*:
      templates:
        icon_color: >
          if (state === 'home') return 'var(--accent-color)';
          return 'var(--disabled-text-color)';
    group.device_*:
      templates:
        icon_color: >
          if (state === 'home') return 'var(--accent-color)';
          return 'var(--disabled-text-color)';

sensor:
  #### SERVER MONITORING #######################################################

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: "/"
      - type: memory_use_percent
      - type: processor_use

  #### COUNT ENTITIES ##########################################################

  - platform: template
    sensors:
      count_automations:
        friendly_name: Automations
        icon_template: mdi:robot
        value_template: "{{ states.automation | count }}"
      count_binary_sensors:
        friendly_name: Binary Sensors
        icon_template: mdi:contrast-circle
        value_template: "{{ states.binary_sensor | count }}"
      count_device_trackers:
        friendly_name: Device Trackers
        icon_template: mdi:radar
        value_template: "{{ states.device_tracker | count }}"
      count_lights:
        friendly_name: Lights
        icon_template: mdi:lightbulb-group
        value_template: "{{ states.light | count }}"
      count_scripts:
        friendly_name: Scripts
        icon_template: mdi:script-text
        value_template: "{{ states.script | count }}"
      count_sensors:
        friendly_name: Sensors
        icon_template: mdi:leak
        value_template: "{{ states.sensor | count }}"
      count_switches:
        friendly_name: Switches
        icon_template: mdi:light-switch
        value_template: "{{ states.switch | count }}"
      count_zones:
        friendly_name: Zones
        icon_template: mdi:map-marker-radius
        value_template: "{{ states.zone | count }}"
