#### CUSTOMIZE #################################################################

homeassistant:
  customize_glob:
    device_tracker.*:
      templates:
        icon_color: >
          if (state === 'home') return 'var(--accent-color)';
          return 'var(--disabled-text-color)';
    group.device_*:
      templates:
        icon_color: >
          if (state === 'home') return 'var(--accent-color)';
          return 'var(--disabled-text-color)';

#### GROUPS ####################################################################

group:
  device_58z72z2:
    name: 58Z72Z2
    icon: mdi:laptop
    entities:
      - device_tracker.58z72z2
      - device_tracker.58z72z2_2
      - device_tracker.58z72z2_3
  device_fafnir:
    name: Fafnir
    icon: mdi:desktop-tower
    entities:
      - device_tracker.fafnir
      - device_tracker.fafnir_2
  device_fenrir:
    name: Fenrir
    icon: mdi:laptop
    entities:
      - device_tracker.fenrir
      - device_tracker.fenrir_2
      - device_tracker.fenrir_3

sensor:
  #### SERVER MONITORING #######################################################

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: "/"
      - type: memory_use_percent
      - type: processor_use

  #### COUNT ENTITIES ##########################################################

  - platform: template
    sensors:
      count_automations:
        friendly_name: Automations
        icon_template: mdi:robot
        value_template: "{{ states.automation | count }}"
      count_binary_sensors:
        friendly_name: Binary Sensors
        icon_template: mdi:contrast-circle
        value_template: "{{ states.binary_sensor | count }}"
      count_device_trackers:
        friendly_name: Device Trackers
        icon_template: mdi:radar
        value_template: "{{ states.device_tracker | count }}"
      count_lights:
        friendly_name: Lights
        icon_template: mdi:lightbulb-group
        value_template: "{{ states.light | count }}"
      count_scripts:
        friendly_name: Scripts
        icon_template: mdi:script-text
        value_template: "{{ states.script | count }}"
      count_sensors:
        friendly_name: Sensors
        icon_template: mdi:leak
        value_template: "{{ states.sensor | count }}"
      count_switches:
        friendly_name: Switches
        icon_template: mdi:light-switch
        value_template: "{{ states.switch | count }}"
      count_zones:
        friendly_name: Zones
        icon_template: mdi:map-marker-radius
        value_template: "{{ states.zone | count }}"

  #### WIREGUARD ###############################################################

  - platform: rest
    resource: http://a0d7b954-wireguard
    name: wireguard_sensor
    value_template: TEST
    json_attributes:
      - Loki
      - Freyja
      - Fenrir
  - platform: template
    sensors:
      wireguard_loki_latest_handshake:
        friendly_name: Loki latest handshak
        icon_template: mdi:handshake
        unit_of_measurement: s
        value_template: "{{ states.sensor.wireguard_sensor.attributes['Loki']['latest_handshake'] }}"
      wireguard_freyja_latest_handshake:
        friendly_name: Freyja latest handshake
        icon_template: mdi:handshake
        unit_of_measurement: s
        value_template: "{{ states.sensor.wireguard_sensor.attributes['Freyja']['latest_handshake'] }}"
      wireguard_fenrir_latest_handshake:
        friendly_name: Fenrir latest handshake
        icon_template: mdi:handshake
        unit_of_measurement: s
        value_template: "{{ states.sensor.wireguard_sensor.attributes['Fenrir']['latest_handshake'] }}"
